/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import page1 from "./page/page1"
import page10 from "./page/page10"
import page11 from "./page/page11"
import page12 from "./page/page12"
import page13 from "./page/page13"
import page14 from "./page/page14"
import Bar from "./components/Bar"
import page15 from "./page/page15"
import Progress from "./components/Progress"
import page16 from "./page/page16"
import ItemLastChooseItem from "./components/ItemLastChooseItem"
import page2 from "./page/page2"
import page3 from "./page/page3"
import page4 from "./page/page4"
import page5 from "./page/page5"
import page6 from "./page/page6"
import page7 from "./page/page7"
import page8 from "./page/page8"
import page9 from "./page/page9"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=1921;
    static height:number=1080;
    static scaleMode:string="fixedwidth";
    static screenMode:string="none";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="pages/page3.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("page/page1.ts",page1);
        reg("page/page10.ts",page10);
        reg("page/page11.ts",page11);
        reg("page/page12.ts",page12);
        reg("page/page13.ts",page13);
        reg("page/page14.ts",page14);
        reg("components/Bar.ts",Bar);
        reg("page/page15.ts",page15);
        reg("components/Progress.ts",Progress);
        reg("page/page16.ts",page16);
        reg("components/ItemLastChooseItem.ts",ItemLastChooseItem);
        reg("page/page2.ts",page2);
        reg("page/page3.ts",page3);
        reg("page/page4.ts",page4);
        reg("page/page5.ts",page5);
        reg("page/page6.ts",page6);
        reg("page/page7.ts",page7);
        reg("page/page8.ts",page8);
        reg("page/page9.ts",page9);
    }
}
GameConfig.init();